version: "3.8"

services:
  servidor-java-final:
    build: .
    container_name: servidor-java-FINAL
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./uploads/imagens:/app/uploads/imagens